### ISSUE TITLE
Usage of FK in DB

### ISSUE THREAD

**Issue by jackxujh** [gcivil-nyu-org/fall2019-cs-gy-6063-team-one#188]
Maybe we should use `Application.job` instead? 
[link](https://github.com/gcivil-nyu-org/fall2019-cs-gy-6063-team-one/blob/e5ec1109b3f138b6c3ac551d0aae7549230a0bd0/applications/views.py#L20)

**Comment by daisycrego** [comment]
I think we ended up making this switch, so I'll go ahead and close this issue
