### ISSUE TITLE
Submitting application bug

### ISSUE THREAD

**Issue by mok232** [gcivil-nyu-org/fall2019-cs-gy-6063-team-one#295]
I think the apply functionality is probably working fine. The problem here is probably with Heroku deleting files uploaded by the user after some time, which a lot of teams have been struggling with.

![image](https://user-images.githubusercontent.com/40494713/69650033-fb182580-103b-11ea-9f30-54f19f8cb3e1.png)

## Expected Behavior

The user should be able to submit an application.

## Current Behavior

The application breaks when clicking the submit application button.

## Ideas for Improvement

Maybe use Amazon S3 to store the files uploaded by the user. This [link](https://devcenter.heroku.com/articles/s3) might be useful.

## Steps to Reproduce

1. Sign in as a candidate with the following
Username: uplyft.demo+isabelgemahe@gmail.com
Password: xCoiKP6nYki9UzR3
2. Go to jobs
3. Click on apply
4. Submit application (with the existing resume file)

**Comment by ahanif19** [comment]
@jackxujh - should we close this? Think it's resolved now
