### ISSUE TITLE
Submit application does not work when using wrong file type for resume/cover letter

### ISSUE THREAD

**Issue by gcivil-nyu** [gcivil-nyu-org/fall2019-cs-gy-6063-team-one#296]
Apply for a job
Select unsupported file type as a file for cover letter/resume
The system gives a message :"See Error Message below"  but there is no actual error message below. 
Looks like the file form silently fails

[Screen video attached](https://github.com/gcivil-nyu-org/fall2019-cs-gy-6063-team-one/files/3892789/wrong_file_apply.mov.zip)

**Comment by ahanif19** [comment]
Resolved - thanks for highlighting
