### ISSUE TITLE
Cannot register with Google (400 error) as candidate

### ISSUE THREAD

**Issue by snehalkenjale** [gcivil-nyu-org/fall2019-cs-gy-6063-team-one#300]
Cannot register with Google as candidate

## Expected Behavior
Should be able to register with Google account

## Current Behavior
Gives 400 oauth google error.
Error: redirect_uri_mismatch

## Steps to Reproduce
1. Go to http://uplyft.herokuapp.com/candidate_login/
2. sign in using google

**Comment by vmoros** [comment]
I'm getting this error too
