### ISSUE TITLE
Getting error while signing up when inactive

### ISSUE THREAD

**Issue by snehalkenjale** [gcivil-nyu-org/fall2019-cs-gy-6063-team-one#301]
Getting error while signing up when inactive

## Expected Behavior
Page should be redirected to signup/login.

## Current Behavior
Gives me TypeError.
![image.png](https://images.zenhubusercontent.com/5d8396cc1201de0001b6a107/12932cf6-fb97-4e30-bf78-129d8ad932ae)
![image.png](https://images.zenhubusercontent.com/5d8396cc1201de0001b6a107/1080ea8e-8e33-49a4-956a-3f241ff6758d)

## Steps to Reproduce
1. go to https://uplyft.herokuapp.com/accounts/inactive/
2. Click sign up
3. fill in the details and submit

**Comment by ahanif19** [comment]
Resolved once Google auth is set up
