### ISSUE TITLE
Doesn't allow valid Phone number

### ISSUE THREAD

**Issue by Vedanth15** [gcivil-nyu-org/fall2019-cs-gy-6063-team-one#302]
I tried to enter a valid phone number, but the application doesn't seem to handle 10-digit- integer-sequence and handles only phone numbers with +1 followed by the integer sequence.

## Expected Behavior
Should accept 10-digit phone number as this application resists within this country, no where I had to select a country and assuming I had to select states from USA, 10 digit number must be valid.

## Current Behavior
Throws an error when I add 10-digit number

## Steps to Reproduce

<img width="946" alt="Phone number bug-uplyft" src="https://user-images.githubusercontent.com/47909391/69661846-23f6e580-1051-11ea-8a88-88ce71694975.PNG">
1. Please see the above image 
2.
3.
4.

**Comment by jackxujh** [comment]
Thank you for your report! We believe this one is a duplicate of #294
