### ISSUE TITLE
No error message below the form field for a wrong file type in `/candidate_profile` page

### ISSUE THREAD

**Issue by alldne** [gcivil-nyu-org/fall2019-cs-gy-6063-team-one#305]
## Expected Behavior
When I upload a resume of which file type is other than pdf, doc, docx, it should show an error message below the file upload form field

## Current Behavior
It only shows `Please correct the error below` at the top of the page but doesn't show which field caused the error. For your information, this functionality works for the errors associated with other form fields like phone number field

## Steps to Reproduce
1. Login
1. Go `/candidate_profile`
1. Upload a wrong file for the resume. e.g a png file

## Context (Environment)
- macOS Catalina 10.15.1
- Google Chrome Version 78.0.3904.108 (Official Build) (64-bit)

**Comment by alldne** [comment]
Very similar issue: #304

**Comment by ahanif19** [comment]
Addressed - thanks
