### ISSUE TITLE
Invalid link on confirmation page if candidate does not provide a portfolio URL

### ISSUE THREAD

**Issue by vmoros** [gcivil-nyu-org/fall2019-cs-gy-6063-team-one#306]
## Expected Behavior
If the applicant did not provide a portfolio URL, the application confirmation page should not have a link to a portfolio.

## Current Behavior
There's an invalid link (http://uplyft.herokuapp.com/applications/None) on the application confirmation page if the applicant did not provide a portfolio URL. The same link is also shown to the employer when they review the application.

## Steps to Reproduce
1. Apply for a job and do not provide a portfolio URL
2. See the application confirmation page. See that it says "Portfolio Website: None" and see that the None part is a link. Click on the link and see an error.
![none link](https://user-images.githubusercontent.com/13837978/69669279-8bb42d00-105f-11ea-8419-110bdfbaad5d.gif)

**Comment by ahanif19** [comment]
Resolved - thanks for pointing this out
