### ISSUE TITLE
No error message when attempting to upload media file as a resume

### ISSUE THREAD

**Issue by YixinHu0321** [gcivil-nyu-org/fall2019-cs-gy-6063-team-one#307]
In profile page, I tried to upload a mp3 file and then the page will show "Please correct the error below." but there's no error message telling me where is the error.

## Expected Behavior
A message should be displayed saying resume uploading was not successful or something.

## Current Behavior
No message.

**Comment by ahanif19** [comment]
Resolved - thank you for highlighting
