### ISSUE TITLE
Not displaying the error message.

### ISSUE THREAD

**Issue by Ayushi-0903** [gcivil-nyu-org/fall2019-cs-gy-6063-team-one#308]
Issue tracker is ONLY used for reporting bugs. New features should be discussed in its own thread on the #general channel of slack.

Unable to apply for the job because of an error while submitting the form. Every time I click on "submit application" my resume gets drop and shows an error msg "Please correct the error below." whereas there's no error message below. I am upload the screenshots of the page after clicking on "Submit Application". 
<img width="1440" alt="Screen Shot 2019-11-26 at 5 11 24 PM" src="https://user-images.githubusercontent.com/55497835/69678439-8cef5500-1073-11ea-9019-f1399ccfb44c.png">
<img width="1440" alt="Screen Shot 2019-11-26 at 5 11 35 PM" src="https://user-images.githubusercontent.com/55497835/69678444-8eb91880-1073-11ea-8552-3facac06ddde.png">
<img width="1440" alt="Screen Shot 2019-11-26 at 5 11 43 PM" src="https://user-images.githubusercontent.com/55497835/69678452-911b7280-1073-11ea-88af-5574a3bb5037.png">

## Expected Behavior
 I am trying to apply for the job and I want to submit the form. I except the form to get submit or indicate what's the error. 

## Current Behavior
I am unable to submit the form. I did fill all the compulsory fields and clicked on submit. But every time I click on "submit application" my resume gets drop and shows an error msg "Please correct the error below." whereas there's no error message below. 

## Ideas for Improvement
 I think you need add something to the resume field. Because I am uploading the big size pdf which can be a possible error. But it is not displaying any error message.

## Context (Environment)
As a user who wants to apply for the job, it is difficult for me to figure out the error on my own and apply for the job. It should display the error message.

**Comment by ahanif19** [comment]
We've addressed this - thanks
