### ISSUE TITLE
Page Redirection

### ISSUE THREAD

**Issue by kavinshah** [gcivil-nyu-org/fall2019-cs-gy-6063-team-one#311]
Issue tracker is ONLY used for reporting bugs. New features should be discussed in its own thread on the #general channel of slack.

When I try to access any page through url without being logged in, it takes to me login page. However, upon logging in, it should take me back to the same url that I was trying to access and not dashboard page.

## Expected Behavior

It should take me to the same url that I was trying to access.

## Current Behavior

Takes me to dashboard page by default upon login

## Steps to Reproduce

1. Enter any valid url without being signed in
2. Provide valid login credentials or sign in using google
3. Check it takes to you your desired page or to default dashboard page

## Context (Environment)

I was trying to go to a desired page directly using a url. Since, I was signed out I needed to log back in. Once logged in, it took me to dashboard page by default and not my desired url page.

**Comment by daisycrego** [comment]
@kavinshah Hi kavin, thanks for the feedback :) We were just wondering, what url(s) did you try out? We're just discussing how we can fix the issue

**Comment by kavinshah** [comment]
@daisycrego 

https://uplyft.herokuapp.com/candidate_profile/
