### ISSUE TITLE
Debug is still active, giving external connections insight into your site structure.

### ISSUE THREAD

**Issue by ab7289** [gcivil-nyu-org/fall2019-cs-gy-6063-team-one#316]
Issue tracker is ONLY used for reporting bugs. New features should be discussed in its own thread on the #general channel of slack.

Going to non-valid URLs displays the site's page structure.

## Expected Behavior
Displays a 404 that doesn't leak site info.

## Current Behavior
Shows all of the URLs, including /admin to external users.

## Ideas for Improvement
turn off debug in production environment.

## Steps to Reproduce
Go to any non-valid URL

## Context (Environment)

leaking site structure in the real world would be a security risk as it would give malicious actors insight into the site structure and where might be vulnerable to attack. Obviously for our case this is a negligible concern, but just thought I'd point it out.

**Comment by ahanif19** [comment]
Pending new file storage
