### ISSUE TITLE
searching for job application in lower case doesnt work

### ISSUE THREAD

**Issue by utkarshp21** [gcivil-nyu-org/fall2019-cs-gy-6063-team-one#319]
## Expected Behavior
Character case should not be considered while searching.

## Current Behavior
Searching for application in pending applications doesn't work with lowercase.

![uplyft2](https://user-images.githubusercontent.com/38756289/69685815-b4521c00-108b-11ea-92c7-1ad3763cab06.gif)

## Steps to Reproduce
1. Dashboard 
2. Pending application 
3. Search application using lower case that has capital case in the name.

**Comment by surajgovardhangaikwad** [comment]
Done
